-- MySQL Script generated by MySQL Workbench
-- Sat 09 Sep 2017 06:41:02 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Xeladevs
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Xeladevs
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Xeladevs` DEFAULT CHARACTER SET utf8 ;
USE `Xeladevs` ;

-- -----------------------------------------------------
-- Table `Xeladevs`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xeladevs`.`Clientes` (
  `idClientes` INT NOT NULL,
  `Nombres` VARCHAR(65) NULL,
  `Apellidos` VARCHAR(65) NULL,
  `DPI` VARCHAR(45) NOT NULL,
  `Telefono` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Xeladevs`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xeladevs`.`Empresa` (
  `idEmpresa` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Web` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Xeladevs`.`Proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xeladevs`.`Proyectos` (
  `idProyectos` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Costo_inicial` VARCHAR(45) NULL,
  `Costo_anual` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `FechaElaboracion` DATE NULL,
  `Repositorio` VARCHAR(85) NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idProyectos`),
  INDEX `fk_Proyectos_Empresa1_idx` (`Empresa_idEmpresa` ASC),
  CONSTRAINT `fk_Proyectos_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `Xeladevs`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Xeladevs`.`Trabajadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xeladevs`.`Trabajadores` (
  `idTrabajadores` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Apellido` VARCHAR(45) NULL,
  `DPI` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NOT NULL COMMENT '		',
  `Celular` VARCHAR(45) NULL,
  `Correo` VARCHAR(45) NULL,
  `Direccion` VARCHAR(45) NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idTrabajadores`),
  INDEX `fk_Trabajadores_Empresa1_idx` (`Empresa_idEmpresa` ASC),
  CONSTRAINT `fk_Trabajadores_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `Xeladevs`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Xeladevs`.`Clientes_has_Proyectos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Xeladevs`.`Clientes_has_Proyectos` (
  `Clientes_idClientes` INT NOT NULL,
  `Proyectos_idProyectos` INT NOT NULL,
  PRIMARY KEY (`Clientes_idClientes`, `Proyectos_idProyectos`),
  INDEX `fk_Clientes_has_Proyectos_Proyectos1_idx` (`Proyectos_idProyectos` ASC),
  INDEX `fk_Clientes_has_Proyectos_Clientes_idx` (`Clientes_idClientes` ASC),
  CONSTRAINT `fk_Clientes_has_Proyectos_Clientes`
    FOREIGN KEY (`Clientes_idClientes`)
    REFERENCES `Xeladevs`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Clientes_has_Proyectos_Proyectos1`
    FOREIGN KEY (`Proyectos_idProyectos`)
    REFERENCES `Xeladevs`.`Proyectos` (`idProyectos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
